# Generated by Django 3.2.7 on 2021-10-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_artesanias',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Imagen del producto'),
        ),
    ]
